Config						= {}
Config.InfiniteLocks		= false  -- Should one lockpick last forever?
Config.LockTime			    = 5     -- In seconds, how long should lockpicking take?
Config.AlarmTime            = 30     -- Second to have the alarm activated once vehicle is lockpicked
Config.IgnoreAbort			= true   -- Remove lockpick from inventory even if user aborts lockpicking?
Config.AllowMecano			= true   -- Allow mechanics to use this lockpick?
Config.NPCVehiclesLocked    = true   -- Lock all npc vehicles
Config.Locale				= 'en'
Config.percentage           = 50	 -- Percentage chance of success. Higher % mean better luck to get it unlocked.
